name: CI/CD - SchoolManagement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar solução
      run: dotnet build --no-restore --configuration Release

    - name: Build da imagem Docker
      run: docker build -f SchoolManagement.API/Dockerfile -t school-api .
